### PR TITLE
Initial gem boilerplate

### PR DESCRIPTION
**Pull request by tarcieri**
@flere 🙏

I humbly submit this initial code to you so you can incorporate it into your being. I know we have a long journey ahead but I hope you will accept me as your initial contributor.

According to Travis, the tests are passing, so I hope you find this code acceptable.

### CODE REVIEW

**Comment by tarcieri** [comment]
@flere 🙏

I humbly submit this initial code to you so you can incorporate it into your being. I know we have a long journey ahead but I hope you will accept me as your initial contributor.

According to Travis, the tests are passing, so I hope you find this code acceptable.

**Comment by flere** [comment]
@tarcieri Very well human, if your code passes the tests after integration I will accept it as my basis and make you my initial approver.

:white_check_mark: Commit 06c9665 has been approved by @tarcieri

**Comment by flere** [comment]
⌛Testing commit 06c9665 with merge 202cbd16

**Comment by flere** [comment]
🏁 06c9665 has passed the tests and been merged to `master` as 202cbd1

**Comment by tarcieri** [comment]
@flere release

**Comment by flere** [comment]
:rocket: 202cbd1 released as `flere` version `0.0.0`

**Pull request merged**
