### PR TITLE
Initial web UI

### PR DESCRIPTION
**Pull request by tarcieri**
Includes a navbar and a placeholder DashboardController

### CODE REVIEW

**Comment by flere** [comment]
✅ Commit 139ca2d has been approved by @tarcieri

**Comment by flere** [comment]
⌛Testing commit 139ca2d with merge 0d3bbd8

**Comment by flere** [comment]
🏁 139ca2d has passed the tests and been merged to `master` as 0d3bbd8

**Comment by tarcieri** [comment]
@flere deploy

**Comment by flere** [comment]
:rocket: 0d3bbd8 has been deployed to https://bot.flere.io/

**Pull request merged**
